### PR TITLE
Prevent retry when remainingChallenges is empty

### PR DESCRIPTION
**Pull request by N0Cloud**
After an error, check if it's possible to retry before returning an retryableErr.
That way it return the real error instead of returning "no solvers available for remaining challenges".

It wasn't my intention, but I think it'll solve #7

### CODE REVIEW

**Comment by mholt** [comment]
Hi, thanks for opening this PR!

I'll try to take a look at it soon. Have you tested to see if it does resolve #7? I haven't gotten a reply about how to reproduce the behavior yet.

**Comment by N0Cloud** [comment]
I can't confirm 100% it's the same issue, but I was having similar logs. You can disable one or two of the ChallengeSolvers in the porcelain example to get similar logs.

Got some time to test correctly so I updated the PR

**Comment by mholt** [comment]
Thanks for verifying and patching; and for the repro instructions. I'll look into this more soon!

**Review by mholt — APPROVED** [review]
LGTM, we can give this a shot. Thanks!

**Pull request merged**
